apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/glroland/trivia.git
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-12-30T02:22:53Z"
  labels:
    app: gamemaster-svc
    app.kubernetes.io/component: gamemaster-svc
    app.kubernetes.io/instance: gamemaster-svc
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: trivia
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  name: gamemaster-svc
  namespace: trivia
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: gamemaster-svc:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /trivia-gamemaster-svc
    git:
      uri: https://github.com/glroland/trivia.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-11-el7
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: gamemaster-svc-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: gamemaster-svc-github-webhook-secret
    type: GitHub
  - type: ConfigChange
