apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"question-svc"}]'
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/glroland/trivia.git
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-10-25T22:42:23Z"
  labels:
    app: app
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: trivia
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: app
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /trivia-app
    git:
      uri: https://github.com/glroland/trivia.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:12
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: app-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: app-github-webhook-secret
    type: GitHub
  - imageChange:
      lastTriggeredImageID: 
    type: ImageChange
  - type: ConfigChange
