apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/glroland/trivia.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: app
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: trivia
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: app
spec:
  lookupPolicy:
    local: false
