apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2020-12-30T02:22:53Z"
  labels:
    app: question-svc
    app.kubernetes.io/component: question-svc
    app.kubernetes.io/instance: question-svc
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: trivia
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  managedFields:
  - apiVersion: route.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.openshift.io/runtime: {}
          f:app.openshift.io/runtime-version: {}
      f:spec:
        f:port:
          .: {}
          f:targetPort: {}
        f:to:
          f:kind: {}
          f:name: {}
          f:weight: {}
        f:wildcardPolicy: {}
    manager: Mozilla
    operation: Update
  - apiVersion: route.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:ingress: {}
    manager: openshift-router
    operation: Update
  name: question-svc
  namespace: trivia
  selfLink: /apis/route.openshift.io/v1/namespaces/trivia/routes/question-svc
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: question-svc
    weight: 100
  wildcardPolicy: None
