apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"question-svc"}]'
    openshift.io/host.generated: "true"
  creationTimestamp: "2020-10-25T22:42:23Z"
  labels:
    app: app
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: trivia
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  managedFields:
  - apiVersion: route.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:ingress: {}
    manager: openshift-router
    operation: Update
    time: "2020-10-25T22:42:23Z"
  - apiVersion: route.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:app.openshift.io/connects-to: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.openshift.io/runtime: {}
          f:app.openshift.io/runtime-version: {}
      f:spec:
        f:port:
          .: {}
          f:targetPort: {}
        f:tls:
          .: {}
          f:caCertificate: {}
          f:certificate: {}
          f:insecureEdgeTerminationPolicy: {}
          f:key: {}
          f:termination: {}
        f:to:
          f:kind: {}
          f:name: {}
          f:weight: {}
        f:wildcardPolicy: {}
    manager: Mozilla
    operation: Update
    time: "2020-10-26T00:11:23Z"
  name: app
spec:
  port:
    targetPort: 8080-tcp
  tls:
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIEKzCCAxOgAwIBAgIUEbl6frxrwvK2aEo0LuyQT2Q2jfEwDQYJKoZIhvcNAQEF
      BQAwgaQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdHZW9yZ2lhMRMwEQYDVQQHDApB
      bHBoYXJldHRhMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxJjAk
      BgNVBAMMHSouYXBwcy5vY3A0LmhvbWUuZ2xyb2xhbmQuY29tMSMwIQYJKoZIhvcN
      AQkBFhRnbHJvbGFuZEBob3RtYWlsLmNvbTAeFw0xOTA5MDkxNDUyMDdaFw0yOTA5
      MDYxNDUyMDdaMIGkMQswCQYDVQQGEwJVUzEQMA4GA1UECAwHR2VvcmdpYTETMBEG
      A1UEBwwKQWxwaGFyZXR0YTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkg
      THRkMSYwJAYDVQQDDB0qLmFwcHMub2NwNC5ob21lLmdscm9sYW5kLmNvbTEjMCEG
      CSqGSIb3DQEJARYUZ2xyb2xhbmRAaG90bWFpbC5jb20wggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQDBMaUXYFa6zsCFzIYs7W4WBfaO0F2fn+FU9MLHEGDX
      Hx3V+P2couI8WnwMm9ToP4Y468QpjZpDrLgZYWx+jCV5yb0nPfSZ7705/Q35NKYo
      G28ZI9Nm266jf/DWZHkmwDZs/DFSjvK6SAzb69WKP6l5I51BjpBUpdbYYc3B8Eh3
      7vrvX/5LCMe6rP00oU40qmXAepOicfx8/6EnwI4mYzwwO20iix0fNduqZMYzrLtb
      2k7qq+viJMBpyyEQfhIaw4hKWBAfkcILnkhAbKI4P1DWl9LmGhDLoLT2SEphqKA+
      M1LOL0NJfxUCjUcIUBiwRZ1Qua3T2OnZV4na1B03Qn9rAgMBAAGjUzBRMB0GA1Ud
      DgQWBBSDaApa+YokQHZRQfE938F6Ob6FmzAfBgNVHSMEGDAWgBSDaApa+YokQHZR
      QfE938F6Ob6FmzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQCC
      J6Ntt20XDLwe49ZFYYHiD6Y5roXjA6TByY2Fta44z7tTFPbhEx0Ky+nKu3KZr7F0
      Sju/X9ri+E9ZsUeYNsU+secRF+CM8XYZW+363KefUDRuKt5lix49asZ2fGadvunP
      uGhRpviwG9kIz9wfMHsdLOAFbvIUvSIJHtqGRIz40apechybtzFGah0FMVRhjqGz
      Q8t5jjpnIJysNc2HVBZx2N8kiiQqIMrRhhE0f7qUM83MzZ5zSgKzpw92gbeAB9pQ
      fbP9ZI2Y2ByjowO/FOFvK3dEhf8hIZdIE22/HhMhPTmixaL/AAQ4SINk8mIt48zb
      l3P4OkjQvGvLF7635AnT
      -----END CERTIFICATE-----
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIEKzCCAxOgAwIBAgIUEbl6frxrwvK2aEo0LuyQT2Q2jfEwDQYJKoZIhvcNAQEF
      BQAwgaQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdHZW9yZ2lhMRMwEQYDVQQHDApB
      bHBoYXJldHRhMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxJjAk
      BgNVBAMMHSouYXBwcy5vY3A0LmhvbWUuZ2xyb2xhbmQuY29tMSMwIQYJKoZIhvcN
      AQkBFhRnbHJvbGFuZEBob3RtYWlsLmNvbTAeFw0xOTA5MDkxNDUyMDdaFw0yOTA5
      MDYxNDUyMDdaMIGkMQswCQYDVQQGEwJVUzEQMA4GA1UECAwHR2VvcmdpYTETMBEG
      A1UEBwwKQWxwaGFyZXR0YTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkg
      THRkMSYwJAYDVQQDDB0qLmFwcHMub2NwNC5ob21lLmdscm9sYW5kLmNvbTEjMCEG
      CSqGSIb3DQEJARYUZ2xyb2xhbmRAaG90bWFpbC5jb20wggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQDBMaUXYFa6zsCFzIYs7W4WBfaO0F2fn+FU9MLHEGDX
      Hx3V+P2couI8WnwMm9ToP4Y468QpjZpDrLgZYWx+jCV5yb0nPfSZ7705/Q35NKYo
      G28ZI9Nm266jf/DWZHkmwDZs/DFSjvK6SAzb69WKP6l5I51BjpBUpdbYYc3B8Eh3
      7vrvX/5LCMe6rP00oU40qmXAepOicfx8/6EnwI4mYzwwO20iix0fNduqZMYzrLtb
      2k7qq+viJMBpyyEQfhIaw4hKWBAfkcILnkhAbKI4P1DWl9LmGhDLoLT2SEphqKA+
      M1LOL0NJfxUCjUcIUBiwRZ1Qua3T2OnZV4na1B03Qn9rAgMBAAGjUzBRMB0GA1Ud
      DgQWBBSDaApa+YokQHZRQfE938F6Ob6FmzAfBgNVHSMEGDAWgBSDaApa+YokQHZR
      QfE938F6Ob6FmzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQCC
      J6Ntt20XDLwe49ZFYYHiD6Y5roXjA6TByY2Fta44z7tTFPbhEx0Ky+nKu3KZr7F0
      Sju/X9ri+E9ZsUeYNsU+secRF+CM8XYZW+363KefUDRuKt5lix49asZ2fGadvunP
      uGhRpviwG9kIz9wfMHsdLOAFbvIUvSIJHtqGRIz40apechybtzFGah0FMVRhjqGz
      Q8t5jjpnIJysNc2HVBZx2N8kiiQqIMrRhhE0f7qUM83MzZ5zSgKzpw92gbeAB9pQ
      fbP9ZI2Y2ByjowO/FOFvK3dEhf8hIZdIE22/HhMhPTmixaL/AAQ4SINk8mIt48zb
      l3P4OkjQvGvLF7635AnT
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: None
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAwTGlF2BWus7AhcyGLO1uFgX2jtBdn5/hVPTCxxBg1x8d1fj9
      nKLiPFp8DJvU6D+GOOvEKY2aQ6y4GWFsfowlecm9Jz30me+9Of0N+TSmKBtvGSPT
      Ztuuo3/w1mR5JsA2bPwxUo7yukgM2+vVij+peSOdQY6QVKXW2GHNwfBId+7671/+
      SwjHuqz9NKFONKplwHqTonH8fP+hJ8COJmM8MDttIosdHzXbqmTGM6y7W9pO6qvr
      4iTAacshEH4SGsOISlgQH5HCC55IQGyiOD9Q1pfS5hoQy6C09khKYaigPjNSzi9D
      SX8VAo1HCFAYsEWdULmt09jp2VeJ2tQdN0J/awIDAQABAoIBAAvM33udC88fP80s
      X+mwmu/Hb3brrTxJxLauuJL2IiQhp23hZoRBwrXTBQ60Gf4Rmz4w0GuFVa3ah+gs
      9jaIkuVseBxEgYNBjHpVRZw6Jgf/HPsZIBmBQ5qC/w/pVSkTxn9DrDORvau5KOfp
      8MIf/1cB4OIXNiOleYj/+FRnO9XvbLrL8L77ZbkTItK/ThLZ0axyBkOzUWGSgLGG
      iDi18VFj/ch6PjZWEDMio0f5pJin3YuWagPrMoMT3rZFbxg8ZCt1zueHAdt8Dwkp
      oC03UPCPyHq9fuArrj9sdZtslczikM/lMwoy518uv/qVBZq+P+4EKHTKaFtnhXRU
      p4B+tykCgYEA6cRFh3oj6VbOY8VxCYkh8tkTZrqgb5FZPiBMZBjjK/H9ruVIbeNk
      WZVFCD8kP/K3JirYt2Byf58JMyNsGvVCnRi+cKlm2PddpZkfKZ5gwszYyF4KsRix
      Fod0Lu1fVZRimEtQmvV6PrWvTLmY5fG2SiGaw6J6RcHYSu03s62zmq8CgYEA05GC
      /bIfuTQrmqgpX3S7pBDtXYbUfK8H5Y2stsuu39/DpceWSicEMBVThDs0efwR0Ljr
      uWCu9sgszoQ+UyFxi1bSUzWU6xgYT/MLIZKMHFbTgM8tItaFj0UFy8cHJqDWsgpB
      Z1PUpQ06H1CBmC/0xha/2hSJOT1tqwQ+OLt9pgUCgYEA4F8ReUpDY7h82ohsyYFF
      A2lVVNm2Gb/Bj37Cs6Srjsdy/UZ28Xo7HDzIiHTKX1KgddLUNZYt785+rwXFwk47
      xLs2Nr5xx7gNu18v6Otp5i9lt1OEIZ0YhA449r3BLkwBIjnPwRvyXHRYMGVHmxUY
      KSj9+d5eS8wVxTzQpPYJGGMCgYA/N+jbY+Fk1vj8kqkiM+Bp6wDyhHpz8105s7bb
      PEu568QrglMfPz9aGtVE2ugYV0D/jHIrh39gkHoLD6sL7h9ekofwgz9HbIC/SxGV
      a5PgV/WFNOL42P85y1crCALUARWGR9g5RuxwkV4/wy+mSRYsJtoXETHb38YoZvEs
      xKGL/QKBgQCKJ3uvkiR1LwvTSJf04hNhPCy11qgXVJxcoqOzV9kIqhnUOoFQzJKM
      1VtLA3wrHK2qm4XVWNFJ/AdzTldE0QNdmiuclkFsgHKJ8ANINCOOmyLAxOVphFdp
      leM16XtkRXO/roZKVZaRjF5nF4UG5tbsplAWgr4Evn607zxIKDgVKA==
      -----END RSA PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: app
    weight: 100
  wildcardPolicy: None
