apiVersion: v1
data:
  database-admin-password: YmZ0cGlsdzJWc0Z5Y1llNw==
  database-name: dHJpdmlhZGI=
  database-password: cGFzc3dvcmQ=
  database-user: dHJpdmlhdXNlcg==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: mongodb-persistent-template
    template.openshift.io/template-instance-owner: aeeb66c8-3ca0-447a-a89d-5a8d9ec7f06a
  name: mongodb
type: Opaque
